#!/usr/bin/env bash
# backup and compress the databases

# Create backup.sql file
mysqldump -u root -p"$1" --all-databases > backup.sql

# Create tar.gz archive
tar -czvf "$(date +%d-%m-%Y).tar.gz" backup.sql
