#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.

file=school
#check if the file exists with -e flag.
if [ -e $file ]; then
    echo "school file exists"
else
    echo "school file does not exist"
fi
# check if the file is empty with  -s flag.
if [ -s $file ]; then
    echo "school file is not empty"
else
    echo "school file is empty"
fi
# check if the file is regular file with -f flag.
if [ -f $file ]; then
    echo "school is a regular file"
fi