#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
	# localhost resolves to 127.0.0.2
	# facebook.com resolves to 8.8.8.8
	# The checker is running on Docker here :
	# http://blog.jonathanargentiero.com/docker-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/

#before running the script, localhost resolves to 127.0.0.1 and facebook.com resolves to 157.240.11.35

#backup the original file : etc/hosts.bak
cp /etc/hosts ~/hosts.new

#configure localhost and facebook @IP
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
#after running the script, localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

# Copy the modified "hosts.new" file to the system's "/etc/hosts" file, overwriting its contents
cp -f ~/hosts.new /etc/hosts
